version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:11.2
    container_name: gocommerce-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # No default, should be set in .env
      MARIADB_DATABASE: ${DB_NAME:-gocommerce}
      MARIADB_USER: ${DB_USERNAME:-gocommerceuser} # Use DB_USERNAME from .env for MariaDB user creation
      MARIADB_PASSWORD: ${DB_PASSWORD:-gocommercepass} # Use DB_PASSWORD from .env for MariaDB password creation
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./storage/mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak for Authentication
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./storage/keycloak/providers:/opt/keycloak/providers
    command: ["start-dev", "--http-port=9000", "--hostname-strict=false", "--http-relative-path=/"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_SCHEMA:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # Admin user for initial setup
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin} # Use KEYCLOAK_ADMIN directly for bootstrap
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-adminpass} # Use KEYCLOAK_ADMIN_PASSWORD directly
      # Realm and Client creation (attempt via environment variables)
      KC_REALM: ${KEYCLOAK_REALM:-gocommerce}
      KC_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-gocommerce-client}
      KC_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-secret}
      # Runtime configuration (may overlap with creation vars)
      KC_HOSTNAME: localhost # Adjust if needed for external access simulation
      KC_HTTP_PORT: ${KEYCLOAK_PORT:-9000} # Ensure internal port matches command
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_TRANSACTION_XA_ENABLED: false
      KC_LOGLEVEL: INFO
    ports:
      - "${KEYCLOAK_PORT:-9000}:${KEYCLOAK_PORT:-9000}" # Expose the correct port
    depends_on:
      keycloak-db:
        condition: service_healthy
    restart: unless-stopped

  keycloak-db:
    image: postgres:latest
    volumes:
      - ./storage/keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_SCHEMA:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5